In [1]:
%autoreload 2 
%matplotlib inline

In [3]:
from __future__ import (print_function, unicode_literals, 
                        division, absolute_import)

In [9]:
import h5py
import pandas as pd
import numpy as np 

In [6]:
import matplotlib.pyplot as plt
import sys
sys.path.append("../")

In [21]:
import extract_catalog as ext_cat
import get_gal_centroids as getg
import plot_clst_prop as plotClst

In [7]:
dataPath = "../../data/"

In [15]:
original_f = h5py.File(dataPath + 
                "Illustris-1_fof_subhalo_myCompleteHaloCatalog_00135.hdf5")

In [17]:
df = ext_cat.extract_clst(original_f, 0)

In [20]:
pos = [k for k in df.keys() if "SubhaloPos" in k]

In [24]:
%pdb

Automatic pdb calling has been turned ON


rotating points by angle xi

In [75]:
df[pos][:10]

SubhaloPos0  SubhaloPos1  SubhaloPos2
0     0.000000     0.000000     0.000000
1  -744.470490 -1607.318359 -1448.265625
2  -167.178101   501.337891 -1121.117188
3   274.732117   238.501953  -138.343750
4    61.319946   360.355469  -767.656250
5   -65.280518   269.515625 -2847.538086
6   591.487854   306.462891  1108.242188
7  -659.313141   206.179688 -2491.986328
8 -1010.009705 -2089.460938 -1561.896484
9   -95.760254   417.144531  -384.330078

In [79]:
along_x = df[pos][:10].apply(lambda x: 
         getg.project_coords(x, xi=0, phi=0, 
                             los_axis=4), axis=1)
along_x = np.array(along_x)
print (along_x[:, :10])

[ 0.  0.  0.]
[ 0.  0.  0.]
[ -744.4704895  -1607.31835938 -1448.265625  ]
[ -167.17810059   501.33789062 -1121.1171875 ]
[ 274.7321167   238.50195312 -138.34375   ]
[  61.31994629  360.35546875 -767.65625   ]
[  -65.28051758   269.515625   -2847.53808594]
[  591.487854     306.46289062  1108.2421875 ]
[ -659.31314087   206.1796875  -2491.98632812]
[-1010.00970459 -2089.4609375  -1561.89648438]
[ -95.76025391  417.14453125 -384.33007812]
[[    0.             0.             0.        ]
 [ 1607.31835938 -1448.265625     744.4704895 ]
 [ -501.33789063 -1121.1171875    167.17810059]
 [ -238.50195312  -138.34375     -274.7321167 ]
 [ -360.35546875  -767.65625      -61.31994629]
 [ -269.515625   -2847.53808594    65.28051758]
 [ -306.46289062  1108.2421875   -591.487854  ]
 [ -206.1796875  -2491.98632812   659.31314087]
 [ 2089.4609375  -1561.89648438  1010.00970459]
 [ -417.14453125  -384.33007812    95.76025391]]
